### PR TITLE
Best command

### PR DESCRIPTION
**Pull request by to266**
Rebased https://github.com/nstinus/nordvpn/pull/25 on pr25 branch and then continued development

### CODE REVIEW

**Comment by nstinus** [comment]
At this point I have mostly remarks regarding form:
- rename best_function to get_best or find_best;
- all two words options should perhaps be hyphenated: --maxload -> --max-load;
- nordvpn best -h should be forwarded to servers.py --help;
- --region option could benefit from the choices keyword in add_argument so that we see them in the help;
- reword the help for maxload and maxping with something like: Filter out servers with load/ping above threshold.
- change --sortload argument with --sort, choices=[load, ping], default = ping;
- if the available regions are in a hard-coded set (used by add_argument(choices)); the reverse keyword could be removed and this is handled outside of the function by passing a positive list of regions;

Tell me what you think.

**Comment by to266** [comment]
I agree on all your points except using choices for region. I'll re-check if that's the case, but it may be that this would prevent using regex.

Currently my idea was to facilitate something along the lines of, for example
```
--region eu --notregion de
```
ie allow excluding certain countries.

**Comment by to266** [comment]
Ready for review

**Comment by to266** [comment]
I rebased this PR on master, so that the branch works with the new API

**Comment by nstinus** [comment]
Squashed and merged your changes. Thank you!

**Pull request closed without merging**
