### PR TITLE
"best", rank uses fping

### PR DESCRIPTION
**Pull request by to266**
- Rank now uses [fping](http://fping.org/) for faster parallel pinging (`pacman -S fping`)
 - Added `best` command. Supports regions, filters the servers by load and then orders by ping.

relevant: https://github.com/nstinus/nordvpn/issues/11

### CODE REVIEW

**Comment by nstinus** [comment]
Thank you for your submission. It is a substantial change. I'll have more time to look at it this week end but one thing that you'll need is to update the documentation as well.

**Comment by to266** [comment]
Added documentation and keyword filtering

**Comment by nstinus** [comment]
I reviewed attentively your contribution and I thank you as it is quite valuable.

I have however a couple of remarks.

I took the liberty of editing the commits as to break them up. Here are the reasons for doing so:
- some had different features combined so I split them;
- dev in one commit, doc, possible typo fix after.

In general, don't commit things that are not related together; it'll make the review much easier as the maintainer can keep some and reject others. Look at git rebase -i for more info.

Couple of issues, open questions:
- Doc is not exhaustive: at least your best command is not mentioned in the synopsis.
- the maxload/ping combination does not seem right to me. With a default maxload=30, my best server is usually with a ping >40ms; I guess I don't really care about the load as long as the ping is good. Perhaps we should get some info from openvpn as I regularly connect to pretty loaded servers and everything is fine for me.

I created a branch in the main repo (pr25). Please review it, address my remarks above and I'll be happy to merge it.

**Comment by to266** [comment]
Sure, I'll rebase to split features into additional commits. 

When looking for a low-ping server where the load is irrelevant, `maxload=100` could be passed. This, however, pings all the servers in the region and takes more time. 

I guess it all depends on which is required at the time: a relatively high-bandwidth (e.g. for netflix and the like) or low ping (e.g. for browsing / chat / ssh). This PR was originally meant to provide a way to find a suitable server for the first use-case.

**Comment by to266** [comment]
Ok I see what you did in your branch.

Only one comment: 
For me, the `+` at the end of the lines (and removing empty lines from the synopsis) does what you wanted in the `FIXME`.

Another idea:
The default `maxload` should be removed. Instead, an option to filter by `maxping` should be added. Also `sortping` and `sortload` should be added. This would facilitate looking for all combinations of ping/load.

**Comment by nstinus** [comment]
Regarding the manpage line breaks, I created a new ticket #31 as it seems it needs to be investigated a bit. Please weigh in there as on my end the + does not work.

I guess maxload is fine, it is just that the default value should be way higher. I am also open for other parameters but we should keep things simple. It is good that people can customize it; but in my opinion, for the general case, it should just work without having to mess around to much.

**Comment by to266** [comment]
I'll close this in favor of the new PR based on your branch

**Pull request closed without merging**
